### ISSUE TITLE
模拟登录并爬取GitHub报错

### ISSUE THREAD

**Issue by YNUYANPENG** [Germey/Python3WebSpider#8]
Germey您好！

很抱歉打扰您，我是一个跟随您GitHub上教程初学爬虫的student。参照您的教程学习模拟登录并爬取GitHub时，遇到一个问题：
Traceback (most recent call last):
  File "D:/PycharmProjects/PRO_Qichacha/github.py", line 56, in <module>
    login.login(email='101305**@qq.com', password='****')
  File "D:/PycharmProjects/PRO_Qichacha/github.py", line 38, in login
    self.profile(response.text)
  File "D:/PycharmProjects/PRO_Qichacha/github.py", line 49, in profile
    name = selector.xpath('//input[@id="user_profile_name"]/@value')[0]
IndexError: list index out of range
代码是参照您给的地址https://github.com/Python3WebSpider/GithubLogin 上复制的，遇到问题后我查阅网上的资料和博客，尝试多种方法后仍不能解决问题，特向您请教，谢谢。

注：我安装的是python3.7,用的IDE为pycharm19.3.3，参照教程，本节之前的相关库安装及环境配置均成功。
期待您的回复，再次表示感谢！

**Comment by Germey** [comment]
GitHub 现在经过多次改版，代码不适配了。

最新 See Issue: https://github.com/Python3WebSpider/GithubLogin/issues/1
